# Generated by Django 5.2.6 on 2025-09-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
